### ISSUE TITLE
Грешки

### ISSUE THREAD

**Issue by MariaGrozdeva** [Angeld55/Algorithms_FMI#2]
DP.txt:
Ред 61: matrix[i-1][j], mаtrix[i][j-1] -> DP[i-1][j], DP[i][j-1]
Ред 67: мисива -> масива
Ред 93: DP[i][j] = DP[i-1][j] или DP[i-1][j - arr[i-1]]] -> DP[i][j] = DP[i-1][j] или DP[i-1][j - arr[i]]]

**Comment by MariaGrozdeva** [comment]
Ред 101: DP[i-1][j - arr[i-1]] -> DP[i-1][j - arr[i]]

**Comment by MariaGrozdeva** [comment]
Без последните две. 
Възстановяването на пътя на 5 задача не връща правилен път

**Comment by Angeld55** [comment]
fixed with commit a92805d,
Thx!
